server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

DATABASE_NAME: cuddly_lamp
DATABASE_USERNAME: root
DATABASE_PASSWORD: 12345